"""github_connections table

Revision ID: 45ce5d528341
Revises: daf5d2562f80
Create Date: 2026-05-25 21:42:42.652811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '45ce5d528341'
down_revision: Union[str, None] = 'daf5d2562f80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_connections',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('scopes', sa.String(length=255), nullable=True),
    sa.Column('github_user_id', sa.BigInteger(), nullable=False),
    sa.Column('github_user_login', sa.String(length=255), nullable=False),
    sa.Column('github_user_avatar_url', sa.Text(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_github_connections_revoked_at_id', 'github_connections', ['revoked_at', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_github_connections_revoked_at_id', table_name='github_connections')
    op.drop_table('github_connections')
    # ### end Alembic commands ###
