"""feature dependencies

Revision ID: b7751ed99d5e
Revises: c2a8d4e7f1b9
Create Date: 2026-05-25 12:26:26.479939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b7751ed99d5e'
down_revision: Union[str, None] = 'c2a8d4e7f1b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_dependencies',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('dependent_id', sa.BigInteger(), nullable=False),
    sa.Column('prerequisite_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('dependent_id <> prerequisite_id', name='ck_feature_dep_no_self'),
    sa.ForeignKeyConstraint(['dependent_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prerequisite_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dependent_id', 'prerequisite_id', name='uq_feature_dep')
    )
    op.create_index('ix_feature_deps_dependent', 'feature_dependencies', ['dependent_id'], unique=False)
    op.create_index('ix_feature_deps_prerequisite', 'feature_dependencies', ['prerequisite_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_feature_deps_prerequisite', table_name='feature_dependencies')
    op.drop_index('ix_feature_deps_dependent', table_name='feature_dependencies')
    op.drop_table('feature_dependencies')
    # ### end Alembic commands ###
