"""clarifications table

Revision ID: daf5d2562f80
Revises: b7751ed99d5e
Create Date: 2026-05-25 12:59:44.276221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'daf5d2562f80'
down_revision: Union[str, None] = 'b7751ed99d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clarifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('raw_md', sa.Text(), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('num_turns', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('total_cost_usd', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clarifications_ticket_id_id', 'clarifications', ['ticket_id', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_clarifications_ticket_id_id', table_name='clarifications')
    op.drop_table('clarifications')
    # ### end Alembic commands ###
